# Input: file
DELETE {
  GRAPH ?g {
   ~file a rdfs:Resource .
   ?ie a rdfs:Resource .
  }
} WHERE {
  GRAPH ?g {
    ~file a nfo:FileDataObject ;
      nie:interpretedAs ?ie .
  }
  FILTER (?g != tracker:FileSystem)
}
