# Inputs: documentsHigh, documentsLow, picturesHigh, picturesLow,
#   audioHigh, audioLow, videoHigh, videoLow, softwareHigh, softwareLow
# Outputs: urn, id
SELECT
  ?urn
  tracker:id(?urn) ?AS ?id
{
  {
    # Data from high priority graphs
    {
      SELECT ?urn { GRAPH tracker:Documents { ?urn a nfo:FileDataObject } } LIMIT ~documentsHigh
    } UNION {
      SELECT ?urn { GRAPH tracker:Pictures { ?urn a nfo:FileDataObject } } LIMIT ~picturesHigh
    } UNION {
      SELECT ?urn { GRAPH tracker:Audio { ?urn a nfo:FileDataObject } } LIMIT ~audioHigh
    } UNION {
      SELECT ?urn { GRAPH tracker:Video { ?urn a nfo:FileDataObject } } LIMIT ~videoHigh
    } UNION {
      SELECT ?urn { GRAPH tracker:Software { ?urn a nfo:FileDataObject } } LIMIT ~softwareHigh
    }
  } UNION {
    # Data from regular priority graphs
    {
      SELECT ?urn { GRAPH tracker:Documents { ?urn a nfo:FileDataObject } } LIMIT ~documentsLow
    } UNION {
      SELECT ?urn { GRAPH tracker:Pictures { ?urn a nfo:FileDataObject } } LIMIT ~picturesLow
    } UNION {
      SELECT ?urn { GRAPH tracker:Audio { ?urn a nfo:FileDataObject } } LIMIT ~audioLow
    } UNION {
      SELECT ?urn { GRAPH tracker:Video { ?urn a nfo:FileDataObject } } LIMIT ~videoLow
    } UNION {
      SELECT ?urn { GRAPH tracker:Software { ?urn a nfo:FileDataObject } } LIMIT ~softwareLow
    }
  }

  FILTER (NOT EXISTS {
    GRAPH tracker:FileSystem { ?urn tracker:extractorHash ?hash }
  })
}
OFFSET ~offset
LIMIT ~limit
