# Inputs: parent
# Outputs: uri
SELECT ?uri {
  GRAPH tracker:FileSystem {
    ?uri a nfo:FileDataObject ;
      nfo:fileName ?fn ;
      nfo:belongsToContainer/nie:isStoredAs ?c .
    FILTER (?c = ~parent) .
    FILTER (STRENDS (?fn, ".cue")) .
  }
}
