SELECT COUNT(?file)
WHERE {
  GRAPH tracker:FileSystem {
    ?file a nfo:FileDataObject ;
          nie:dataSource/tracker:available true .
    FILTER (! EXISTS { ?file nie:interpretedAs/rdf:type nfo:Folder })
  }
}
