SELECT ?tag ?label nao:description(?tag) COUNT(?urns)
WHERE {
  ?tag a nao:Tag ;
    nao:prefLabel ?label .
  OPTIONAL {
    ?urns nao:hasTag ?tag
  } .
}
GROUP BY ?tag
ORDER BY ASC(?label)
OFFSET ~offset
LIMIT ~limit
