SELECT ?image ?u
WHERE {
  GRAPH tracker:Pictures {
    ?image a nfo:Image ;
      nie:isStoredAs ?u .
    ?u nie:dataSource ?ds .
    OPTIONAL {
      ?ds tracker:available ?available
    }
  }
  FILTER (~showAll^^xsd:boolean || ?available)
}
ORDER BY ASC(?u)
OFFSET ~offset
LIMIT ~limit
