SELECT ?software ?u
WHERE {
  GRAPH tracker:Software {
    ?software a nfo:Software ;
      nie:isStoredAs ?u .
    ?u nie:dataSource ?ds .
    OPTIONAL {
      ?ds tracker:available ?available
    }
  }
  FILTER (~showAll^^xsd:boolean || ?available)
}
ORDER BY ASC(?u)
OFFSET ~offset
LIMIT ~limit
