SELECT
  COUNT(?urn)
{
  GRAPH ?g { ?urn a nfo:FileDataObject . }

  FILTER (?g != tracker:FileSystem) .
  FILTER (NOT EXISTS {
    GRAPH tracker:FileSystem { ?urn tracker:extractorHash ?hash }
  }) .
}
