# Output: file, isRemovable, isOptical, available
SELECT
  ?file ?isRemovable
{
  GRAPH tracker:FileSystem {
    ?vol a tracker:IndexedFolder ;
       nie:isStoredAs ?file ;
    BIND (tracker:isRemovable(?vol) AS ?isRemovable) .
  }
}
