# Inputs: uri

# Delete all information elements for the given data object
DELETE WHERE {
  GRAPH ?g {
    ~uri a rdfs:Resource ;
      nie:interpretedAs ?ie .
    ?ie a rdfs:Resource .
  }
};

# Ensure there are no stale resources keeping the inverse relation
DELETE WHERE {
  GRAPH ?g {
    ?ie a rdfs:Resource ;
      nie:isStoredAs ~uri .
  }
};

# Delete extractorHash, to ensure the file is extracted again.
DELETE WHERE {
  GRAPH tracker:FileSystem {
    ~uri tracker:extractorHash ?h .
  }
}
