# Inputs: isRemovable, isOptical
DELETE {
  GRAPH ?g {
    ?f a rdfs:Resource .
    ?ie a rdfs:Resource
  }
} WHERE {
  ?v a tracker:IndexedFolder ;
    tracker:isRemovable ~isRemovable ;
    tracker:isOptical ~isOptical .
  ?f nie:dataSource ?v .
  GRAPH ?g {
    ?ie nie:isStoredAs ?f
  }
}
